[versions]
kotlinxCoroutines = "1.6.4"
mixinExtras = "0.0.12"
kodein = "7.12.0"
ueventbus = "1.0.0"
deftils = "2.0.0"
caffeine = "2.9.3"
websocket = "1.5.2"
quicksocket = "1.2.2"
okhttp = "4.9.3"
configured = "1.0.0-beta.4"
universalcraft = "181"
elementa = "441"
nedit = "2.1.1"
hypixelapi = "4.2"
